PROJECT_NAME := TStick
EXTRA_COMPONENT_DIRS := external/libmapper_idf/components external/GestureLooper/components external/GestureLooper/external/esp32-idf-blemidi/components 
include $(IDF_PATH)/make/project.mk
