M48
; DRILL file {KiCad 7.0.6} date Tue Oct 17 01:06:07 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-17T01:06:07-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.1463Y-2.2661
X4.1463Y-2.4937
T2
X4.0642Y-2.0272
X4.0642Y-2.7272
T0
M30
